---
- name: playbook for creating users
  hosts: all
  become: true
  vars_files:
    - user.yml
  tasks:
  - name: creating user {{ user }}
    user: 
      name: "{{ user }}"
    with_items: "{{ user }}"
