---
- name: Seup tomcat
  hosts: all
  become: true
  tasks:
  - name: Install java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on ubuntu
    apt: 
      name: default-jdk
      state: present 
    when: ansible_os_family == "Debian"

  - name: Download tomcat packages
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.58/bin/apache-tomcat-8.5.58.tar.gz
      dest: /opt

  - name: Untar tomcat
    unarchive:
      src: /opt/apache-tomcat-8.5.58.tar.gz
      dest: /opt
      remote_src: yes
 
  - name: Add execution permission on startup.sh
    file:
      path: /opt/apache-tomcat-8.5.58/bin/startup.sh
      mode: 0777

  - name: start tomcat services
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.58/bin
 
  
